#!/usr/bin/env python3
"""Convert a supported mono NAM LSTM into typed float32 C++ model data."""

import argparse
import hashlib
import json
import math
from pathlib import Path
import struct


def convert(source):
    raw = Path(source).read_bytes()
    model = json.loads(raw)
    if not isinstance(model, dict):
        raise ValueError("model must be a JSON object")
    if model.get("version") not in ("0.5.4", "0.6.0"):
        raise ValueError("supported NAM versions: 0.5.4, 0.6.0")
    if model.get("architecture") != "LSTM" or model.get("sample_rate") != 48000:
        raise ValueError("model must be a 48 kHz LSTM")
    config = model["config"]
    if not isinstance(config, dict):
        raise ValueError("config must be a JSON object")
    allowed = {"input_size", "hidden_size", "num_layers", "in_channels", "out_channels"}
    if set(config) - allowed:
        raise ValueError("unsupported LSTM config fields")
    for key in ("input_size", "num_layers", "in_channels", "out_channels"):
        value = config.get(key, 1) if key.endswith("channels") else config.get(key)
        if type(value) is not int or value != 1:
            raise ValueError("only single-layer, mono, non-parametric LSTMs are supported")
    hidden = config.get("hidden_size")
    if type(hidden) is not int or not 1 <= hidden <= 8:
        raise ValueError("hidden_size must be an integer from 1 to 8")
    weights = model["weights"]
    # Gates, biases, initial hidden/cell state, then output head and bias.
    count = 4 * hidden * (1 + hidden) + 6 * hidden + hidden + 1
    if not isinstance(weights, list) or len(weights) != count:
        raise ValueError(f"expected {count} weights")
    literals = []
    for weight in weights:
        if type(weight) not in (int, float) or not math.isfinite(weight):
            raise ValueError("weights must be finite numbers")
        value = struct.unpack("<f", struct.pack("<f", weight))[0]
        if not math.isfinite(value):
            raise ValueError("weight is outside float32 range")
        literals.append(value.hex() + "f")
    digest = hashlib.sha256(raw).hexdigest()
    lines = ["// Generated by scripts/convert_lstm.py; do not edit.",
             f"// Source SHA-256: {digest}", "#pragma once", "",
             "namespace embedded_model {",
             f"inline constexpr int kHiddenSize = {hidden};",
             "inline constexpr double kSampleRate = 48000.0;",
             f'inline constexpr char kSourceSha256[] = "{digest}";',
             "inline constexpr float kWeights[] = {"]
    lines.extend("  " + ", ".join(literals[i:i + 4]) + ","
                 for i in range(0, len(literals), 4))
    lines.extend(["};", "} // namespace embedded_model", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        result = convert(args.input)
    except (ValueError, KeyError, TypeError, OverflowError, OSError) as error:
        parser.error(str(error))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(result)


if __name__ == "__main__":
    main()
