#!/usr/bin/env python3
"""Embed the required 48 kHz A2-Lite models without a runtime JSON parser."""

import argparse
import hashlib
import json
import math
from pathlib import Path
import struct

FILES = ("fender-twin65-a2-lite.nam", "vox-ac30-chimey-a2-lite.nam",
         "marshall-jcm800-g5-a2-lite.nam")
KERNELS = [6] * 14 + [15, 15] + [6] * 7
DILATIONS = [1, 3, 7, 17, 41, 101, 239] * 2 + [1, 13] + [1, 3, 7, 17, 41, 101, 239]


def expected_layer():
    layer = dict(input_size=1, condition_size=1, channels=3, bottleneck=3,
                 head=dict(out_channels=1, kernel_size=16, bias=True),
                 kernel_sizes=KERNELS, dilations=DILATIONS,
                 activation=[dict(type="LeakyReLU", negative_slope=0.01)] * 23,
                 head1x1=dict(active=False, out_channels=1, groups=1),
                 layer1x1=dict(active=True, groups=1), groups_input=1,
                 groups_input_mixin=1, gating_mode=["none"] * 23,
                 secondary_activation=[None] * 23, slimmable=None)
    for name in ("conv_pre", "conv_post", "input_mixin_pre", "input_mixin_post",
                 "activation_pre", "activation_post", "layer1x1_post", "head1x1_post"):
        layer[name + "_film"] = dict(active=False, shift=True, groups=1)
    return layer


def convert(path):
    raw = path.read_bytes()
    model = json.loads(raw)
    if (model.get("version") != "0.7.0" or model.get("architecture") != "WaveNet"
            or model.get("sample_rate") != 48000):
        raise ValueError(f"{path}: expected NAM 0.7.0, 48 kHz WaveNet")
    config = model["config"]
    if (set(config) != {"layers", "head", "head_scale"}
            or config["layers"] != [expected_layer()] or config["head"] is not None):
        raise ValueError(f"{path}: unsupported A2-Lite configuration")
    weights = model["weights"]
    if len(weights) != 1871:
        raise ValueError(f"{path}: expected 1871 weights")
    floats = []
    for value in weights:
        if type(value) not in (int, float) or not math.isfinite(value):
            raise ValueError(f"{path}: invalid weight")
        value = struct.unpack("<f", struct.pack("<f", value))[0]
        if not math.isfinite(value):
            raise ValueError(f"{path}: weight outside float32 range")
        floats.append(value)
    # Offline rearrangement only: Conv1D [out][in][tap] -> [tap][in][out].
    packed = floats[:3]
    offset = 3
    for kernel in KERNELS:
        packed += [floats[offset + (out * 3 + inp) * kernel + tap]
                   for tap in range(kernel) for inp in range(3) for out in range(3)]
        offset += 9 * kernel
        packed += floats[offset:offset + 18]  # bias, mixin, residual matrix/bias
        offset += 18
    packed += [floats[offset + inp * 16 + tap] for tap in range(16) for inp in range(3)]
    packed += floats[offset + 48:]  # head bias and authoritative weight-stream scale
    assert len(packed) == 1871
    return packed, hashlib.sha256(raw).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--models", type=Path, default=Path("models/local"))
    args = parser.parse_args()
    lines = ["// Generated by scripts/convert_a2.py; do not redistribute model weights.",
             "#pragma once", "namespace embedded_a2 {"]
    try:
        for index, name in enumerate(FILES):
            weights, digest = convert(args.models / name)
            lines += [f"// {name}; SHA-256 {digest}",
                      f"inline constexpr float kWeights{index}[] = {{"]
            lines += ["  " + ", ".join(x.hex() + "f" for x in weights[i:i + 4]) + ","
                      for i in range(0, len(weights), 4)]
            lines += ["};"]
    except (OSError, ValueError, KeyError, TypeError, OverflowError) as error:
        parser.error(str(error))
    lines += ["}", ""]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
